### PR TITLE
0.10.1 add french and update documentation

### PR DESCRIPTION
**Pull request by RannyBergamotte**
Adds French Translations
Minor Changes to English localization file

Update README.md to include the new plugins. Also sorts them by plugin list order in Desmodder (btw on this I think the Desmodder menu for plugins should be re-ordered)

Rewrote INSTALLATION.md to be much more clear

### CODE REVIEW

**Comment by RannyBergamotte** [comment]
Oops, realized there is a typo on line 15 of installation.md, the not te, and also forgot that I wanted to add a small note about how web store is recommended as it auto-updates.

Also forgot to double check captilization with french translation, told myself I would do that at the end of translating before PR, but forgot. 

I'll get those stuff fixed and submit a new PR i guess, let me know though if you spot anything else that could be changed.

**Comment by jared-hughes** [comment]
You won't need to submit a new pull request. If you push some new commits to the same branch, they will appear here as well.

**Comment by jared-hughes** [comment]
However, I would appreciate if you split the documentation changes into a separate PR. That would ensure the commits end up cleaner and helps me review them separately.

**Comment by RannyBergamotte** [comment]
Closing in favor of PR #541

**Pull request closed without merging**
