### PR TITLE
Show IDs in Text Mode with Debug Mode enabled

### LINKED ISSUE #693: Text Mode Debug Mode
Simple: When Debug Mode is enabled, show expression IDs instead of indices in Text Mode.

### PR DESCRIPTION
**Pull request by jared-hughes**
There might currently be no way to get a difference between IDs and indices while in text mode. 
But merging with https://github.com/DesModder/DesModder/pull/695 allows for actually testing this code:

image

Fixes #693

### CODE REVIEW

**Comment by radian628** [comment]
Sorry for the late review! I just tried to test this on the graphing calc, but I can't seem to get the IDs to show up in Text Mode even though Debug Mode is enabled. Text Mode also seems to automatically switch the IDs to an increasing sequence of integers when one switches out of it. Not sure if this is intentional and it's doing that because those _are_ the IDs now.

**Comment by radian628** [comment]
For context, I'm on Windows 11 and Microsoft Edge.

**Comment by radian628** [comment]
Oh wait, is this specifically designed to work in combination with #695? I might be misunderstanding.

**Comment by jared-hughes** [comment]
Sorry this was confusing. Yes, Text Mode defaults to the IDs being equal to the index. The only IDs it keeps are those which are not simply digits. E.g. it preserves `**dcg-geo-folder**`. So the constructions folder gets preserved through Text Mode:
image

**Pull request merged**
