### PR TITLE
Fix better evaluation for complex numbers

### LINKED ISSUE #942: Complex numbers can't be shown with Better Evaluation View
Screenshot_5
All complex numbers are shown as NaN in lists

### PR DESCRIPTION
**Pull request by SlimRunner**
It fixes #942 (Complex numbers can't be shown with Better Evaluation View)

### CODE REVIEW

**Comment by SlimRunner** [comment]
Link to the test graph: https://www.desmos.com/calculator/oanjvdr3df

**Comment by SlimRunner** [comment]
I need to discuss about this (hence why I made it a draft)

image

Message is in progress...

**Comment by jared-hughes** [comment]
I looked a bit into differentiating the zeroes. Ended up being more work than expected because the displayed values are calculated in the worker instead of the main page, and the worker doesn't know if better evaluation is enabled. So I gave up. For reference, the relevant code is matched in replacements with
````md
*Find* => `current`
```js
// `real` and `imag` are strings or undefined here.
$real && $imag
  ? `${$real}${$val[1] >= 0 ? "+" : "-"}${$imag !== "1" ? `${$imag}` : ""}i`
  : $imag
  ? `${$val[1] >= 0 ? "" : "-"}${$imag !== "1" ? `${$imag}` : ""}i`
  : $real != null
  ? $real
  : "0"
```
````

**Review by jared-hughes — APPROVED** [review]
Looks great :)

**Pull request merged**
