### PR TITLE
Fix draw order lookup in Intellisense

### PR DESCRIPTION
**Pull request by SlimRunner**
This patch fixes the Intellisense lookup which currently fails to sort the items by drawing order because Desmos removed a property from Calc.

The property removed was the `Calc.controller.listModel.drawOrder`. It's changed to `Calc.controller.listModel.drawLayers[...].drawOrder`. I am not sure why `drawLayers` is an array instead of an object, but I opened several graphs and they all had only one element. Maybe it's future proofing for later, but whatever the case I hardcoded the zero in the intellisense plugin.

### CODE REVIEW

**Comment by jared-hughes** [comment]
I suspect it's for the "in front of everything" checkbox: https://www.desmos.com/calculator/ow9zkgenlp

**Comment by SlimRunner** [comment]
Oh shut. I could cause the ordering to be unstable. I think a simple reduction should suffice.

**Comment by SlimRunner** [comment]
I think that should be it. If you need another change let me know.

**Comment by jared-hughes** [comment]
Now I'm wondering why Intellisense uses the draw order at all. Shouldn't it just use index order in the expressions list (@radian628?)?. Now that they're distinct, this actually matters. That would simplify this sorting code.

**Comment by SlimRunner** [comment]
I was so focused on leaving the code as unaltered, I didn't stop to think. Yeah, now (more than before) would make more sense to sort by index.

**Comment by SlimRunner** [comment]
Oh, here is a think I did not consider. @radian628 , the intellisense menu gets updated each time it is invoked (by typing), right?

I ask because if it doesn't then I just introduced indexes that can go stale.

**Review by jared-hughes — APPROVED** [review]
So simple now! Looks great

**Pull request merged**
